
package view;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Dimitri Wegner
 */
public abstract class ContentPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = -7898965622329822457L;
	
	private List<IContentCallback> callbacks;

    /** Creates new form ContentPanel */
    public ContentPanel() {
        callbacks = new ArrayList<IContentCallback>();

        initComponents();
    }

    /**
     *  Setzt das Callbackobjekt zur Kommunikation mit dem Mainframe
     * @param callback Callbackobjekt
     */
    public void addCallbackListener(IContentCallback callback) {
        callbacks.add(callback);
    }

    /**
     * Status des Callbacks
     *
     * @param success Status des Callbacks
     */
    public void fireCallbackEvent(boolean success) {
        for (IContentCallback c : callbacks) {
            c.processFinished(success);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
