/*
 * SplashScreen.java
 *
 * Created on 04.03.2009, 00:11:21
 */
package view;

/**
 * Zeigt das Logo der Anwendung. Wird beim Starten der Anwendung angezeigt,
 * solange im Hintergrund verschiedene Initialisierungsprozesse laufen.
 *
 * @author Dimitri Wegner
 */
public class SplashScreen extends javax.swing.JDialog implements Runnable {

	private static final long serialVersionUID = 935610779163991437L;
	
	/** Erstellt einen neuen SplashScreen Dialog */
    public SplashScreen() {
        super(null, ModalityType.MODELESS);
    }

    /** Initialisiert die Komponenten und zeigt die Form. */
    public void run() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splashScreen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(control.MainApplication.class).getContext().getResourceMap(SplashScreen.class);
        setTitle(resourceMap.getString("splashScreenDialog.title")); // NOI18N
        setAlwaysOnTop(true);
        setIconImage(null);
        setName("splashScreenDialog"); // NOI18N
        setResizable(false);
        setUndecorated(true);

        splashScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/splashscreen.png"))); // NOI18N
        splashScreen.setLabelFor(splashScreen);
        splashScreen.setName("splashScreen"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splashScreen)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splashScreen)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel splashScreen;
    // End of variables declaration//GEN-END:variables
}
