package view.tools;

import java.util.ArrayList;
import java.util.List;

/**
 * Zeigt eine Liste von Nachrichten, die zB verwendet werden kann, um
 * Fehler anzuzeigen, die bei der Eingaben von Daten in ein Formular auftauchen.
 *
 * @author Dimitri Wegner
 */
public class MessagePanel extends javax.swing.JPanel {

	private static final long serialVersionUID = -6137585028151030512L;
	
	String header = "Fehler";
    List<String> msgList;

    /** Erstellt neues MessagePanel */
    public MessagePanel() {
        msgList = new ArrayList<String>();

        initComponents();
    }

    /**
     * Erzeugt ein neues MessagePanel mit einer Überschrift.
     *
     * @param header Überschrift
     */
    public MessagePanel(String header) {
        this();
        this.header = header;
    }

    /**
     * Fügt eine neue Nachricht zum Panel hinzu.
     * @see #renderText()
     * @param msg Nachricht
     */
    public void addMessage(String msg) {
        msgList.add(msg);
    }

    /**
     * Entfernt die i-te Nachricht von dem Panel.
     * @param i Index der Nachricht
     */
    public void removeMessage(int i) {
        msgList.remove(i);
    }

    /** Löscht alle Nachrichten aus dem Panel. */
    public void clear() {
        msgList.clear();
    }

    /**
     * Zeigt alle Nachrichten auf dem Panel.
     * (!) Nicht vergessen dabei validate() aufzurufen, falls MessagePanel
     * sich in einem anderen Panel befindet, sonst muss pack() aufgerufen
     * werden, damit die Größe richtig setzt wird.
     */
    public void renderText() {
        if (msgList.isEmpty()) {
            msgLabel.setText("");
        } else {
            StringBuffer text =
                    new StringBuffer("<html><font size=3><ol>");
            for (String s : msgList) {
                text.append("<li>" + s + "</li>");
            }
            text.append("</ul></font></html>");
            msgLabel.setText(text.toString());
            this.validate();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgLabel = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        msgLabel.setName("msgLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(msgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(msgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel msgLabel;
    // End of variables declaration//GEN-END:variables
}
